# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__ = 'unknown'
__repo_version__ = 'unknown'
__fingerprint__ = '1c07ab08fa9044bc93aa49a726a3d904579b22c1 *'
__dependency_versions__ = {
    'boost': '1.60.lsst1+2',
    'python': 'unknown',
    'boost_regex': '1.60.lsst1+2',
    'base': '6.0b1-hsc+7',
    'pex_exceptions': '6.0b0-hsc+10',
    'numpy': '1.13.1',
    'utils': '6.2-hsc+1',
    'daf_base': '6.0b5-hsc+3',
    'log4cxx': '0.10.0.lsst7',
    'log': '6.0b1-hsc+9',
    'boost_system': '1.60.lsst1+2',
    'boost_filesystem': '1.60.lsst1+2',
    'pex_policy': '6.0b0-hsc+13',
    'mariadbclient': '10.1.21.lsst2',
    'boost_serialization': '1.60.lsst1+2',
    'daf_persistence': '6.0b5-hsc+3',
    'pex_config': '6.0b1-hsc+9',
    'eigen': '3.2.5.lsst3',
    'fftw': '3.3.4.lsst2',
    'ndarray': '1.3.3.lsst1',
    'minuit2': '5.34.14',
    'gsl': '2.4',
    'cfitsio': '3360.lsst5',
    'starlink_ast': 'lsst-dev-gc8b18833b2',
    'astshim': '6.0b6-hsc+1',
    'afw': '6.2-hsc+1',
}
__all__ = (
    '__version__',
    '__repo_version__',
    '__fingerprint__',
    '__dependency_versions__',
)
